version: '3'
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile_apache
    volumes:
      - ../share/apache:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile_mysql
    volumes:
      - ../share/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
