version: '3'
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile_apache
    container_name: web
    volumes:
      - ../share/apache:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile_mysql
    container_name: db
    volumes:
      - ../share/mysql:/var/lib/mysql
      - ../share/sql/:/var/tmp/workdir
    ports:
      - "13306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_ROOT_PASSWORD: ''
